Use shell commands instead of file

diff --git a/.github/workflows/tf-apply.yml b/.github/workflows/tf-apply.yml
--- a/.github/workflows/tf-apply.yml
+++ b/.github/workflows/tf-apply.yml
@@ -62,8 +62,19 @@ jobs:
       - name: Run Terragrunt apply
         run: |
 
-            # Assume env-appropriate role
-            source ./terragrunt/assume-role.sh ${{ secrets.ROLE_ARN }} ${{ github.run_id }}
+            # Assume the env IAM role and get temporary credentials
+            CREDENTIALS=$(aws sts assume-role --role-arn "${{ secrets.ROLE_ARN }}" --role-session-name "${{ github.run_id }}")
+
+            # Check if the assume-role command was successful
+            if [ $? -ne 0 ]; then
+                echo "Failed to assume role"
+                exit 1
+            fi
+
+            # Extract the temporary credentials from the JSON response
+            export AWS_ACCESS_KEY_ID=$(echo "${CREDENTIALS}" | jq -r '.Credentials.AccessKeyId')
+            export AWS_SECRET_ACCESS_KEY=$(echo "${CREDENTIALS}" | jq -r '.Credentials.SecretAccessKey')
+            export AWS_SESSION_TOKEN=$(echo "${CREDENTIALS}" | jq -r '.Credentials.SessionToken')
 
             # Source parameter store vars via chamber
             export ENVIRONMENT="${{ inputs.environment }}"
