Clean up, Improvement and Updates

diff --git a/.github/workflows/tf-plan-apply.yml b/.github/workflows/tf-plan-apply.yml
--- a/.github/workflows/tf-plan-apply.yml
+++ b/.github/workflows/tf-plan-apply.yml
@@ -51,11 +51,11 @@ jobs:
       - name: Assume Terraform Role
         id: assume-terraform-role
         run: |
-            creds=$(aws sts assume-role --role-arn ${{ secrets.TF_ROLE_ARN }} --role-session-name ${{ github.run_id }})
+            creds=$(aws sts assume-role --role-arn ${{ secrets.ROLE_ARN }} --role-session-name ${{ github.run_id }})
 
             if [ $? -ne 0 ]; then
-            echo "Failed to assume role: $credentials"
-            return 1
+            echo "Failed to assume role: $creds"
+            exit 1
             fi
 
             export AWS_ACCESS_KEY_ID=$(echo $creds | jq -r .AccessKeyId)
@@ -135,7 +135,7 @@ jobs:
       - name: Assume Terraform Role
         id: assume-terraform-role
         run: |
-          aws sts assume-role --role-arn ${{ secrets.TF_ROLE_ARN }} --role-session-name git --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text
+          aws sts assume-role --role-arn ${{ secrets.ROLE_ARN }} --role-session-name git --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text
 
       - name: Download plan output artifact
         uses: actions/download-artifact@v4
