Try aws configure for role-chaining

diff --git a/.github/workflows/tf-plan-apply.yml b/.github/workflows/tf-plan-apply.yml
--- a/.github/workflows/tf-plan-apply.yml
+++ b/.github/workflows/tf-plan-apply.yml
@@ -53,12 +53,29 @@ jobs:
           role-session-name: OIDC
 
       - name: Assume Terraform Role
+        run: |
+            creds="$(aws sts assume-role --role-arn ${{ secrets.ROLE_ARN }} --role-session-name ${{ github.run_id }})"
+
+            if [ $? -ne 0 ]; then
+            echo "Failed to assume role: $creds"
+            exit 1
+            fi
+
+            export AWS_ACCESS_KEY_ID=$(echo $creds | jq -r .AccessKeyId)
+            export AWS_SECRET_ACCESS_KEY=$(echo $creds | jq -r .SecretAccessKey)
+            export AWS_SESSION_TOKEN=$(echo $creds | jq -r .SessionToken)
+        
+            echo "AWS_ACCESS_KEY_ID=$(echo $creds | jq -r .AccessKeyId)" >> $GITHUB_ENV
+            echo "AWS_SECRET_ACCESS_KEY=$(echo $creds | jq -r .SecretAccessKey)" >> $GITHUB_ENV
+            echo "AWS_SESSION_TOKEN=$(echo $creds | jq -r .SessionToken)" >> $GITHUB_ENV
+
+      - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-region: ${{ vars.AWS_REGION }}
-          role-to-assume: ${{ secrets.ROLE_ARN }}
-          role-session-name: ${{ github.run_id }}
-
+          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
+          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
 
       - name: Source env vars using Chamber
         run: |
