fixup for role-chaining & env sourcing

diff --git a/.github/workflows/tf-plan-apply.yml b/.github/workflows/tf-plan-apply.yml
--- a/.github/workflows/tf-plan-apply.yml
+++ b/.github/workflows/tf-plan-apply.yml
@@ -46,18 +46,31 @@ jobs:
         with:
           aws-region: ${{ vars.AWS_REGION }}
           role-to-assume: ${{ secrets.GH_ROLE_ARN }}
-          role-session-name: git
+          role-session-name: OIDC
 
       - name: Assume Terraform Role
         id: assume-terraform-role
         run: |
-            aws sts assume-role --role-arn ${{ secrets.TF_ROLE_ARN }} --role-session-name git --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text          
+            creds=$(aws sts assume-role --role-arn ${{ secrets.TF_ROLE_ARN }} --role-session-name git --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output json)
+            export AWS_ACCESS_KEY_ID=$(echo $creds | jq -r .AccessKeyId)
+            export AWS_SECRET_ACCESS_KEY=$(echo $creds | jq -r .SecretAccessKey)
+            export AWS_SESSION_TOKEN=$(echo $creds | jq -r .SessionToken)
+        
+            echo "AWS_ACCESS_KEY_ID=$(echo $creds | jq -r .AccessKeyId)" >> $GITHUB_ENV
+            echo "AWS_SECRET_ACCESS_KEY=$(echo $creds | jq -r .SecretAccessKey)" >> $GITHUB_ENV
+            echo "AWS_SESSION_TOKEN=$(echo $creds | jq -r .SessionToken)" >> $GITHUB_ENV
 
       - name: Source env vars using Chamber
         run: |
-          export ENVIRONMENT="${{ inputs.environment }}"
-          eval $(chamber env $ENVIRONMENT)
-          echo "Environment variables loaded."
+            export ENVIRONMENT="${{ inputs.environment }}"
+            eval $(chamber env $ENVIRONMENT)
+        
+            if [ $? -ne 0 ]; then
+            echo "Failed to load environment variables."
+            exit 1
+            fi
+            
+            echo "Environment variables loaded successfully."
 
       - name: Initialize Terragrunt
         run: |
